apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: guestbook
spec:
 generators:
 - list:
     elements:
     - cluster: engineering-alpha
       url: https://172.24.254.191:6443
     - cluster: engineering-beta
       url: https://172.24.252.233:6443
 template:
   metadata:
     name: '{{cluster}}-guestbook'
   spec:
     project: default
     source:
       repoURL: https://github.com/MingZhang-YBPS/applicationset-example.git
       targetRevision: HEAD
       path: list-generator/guestbook/{{cluster}}
     destination:
       server: '{{url}}'
       namespace: guestbook
